name: Deploy Develop Branch from Bitbucket

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch of the GitHub repository.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org" > ~/.git-credentials

      - name: Clone Bitbucket repository and checkout develop branch
        run: |
          git clone https://cminds1122@bitbucket.org/studentmanagementtool/cms.git bitbucket-repo
          cd bitbucket-repo
          git fetch
          git checkout development

      - name: Install dependencies
        run: |
          cd bitbucket-repo/cms
          npm install  # Adjust if using a different package manager

      - name: Build project
        run: |
          cd bitbucket-repo/cms
          npm run build  # Adjust according to your build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./build  # Directory containing the build output
          publish_branch: gh-pages  # Branch where GitHub Pages is deployed
